package tftpsrv

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"io"
	"net"
	"strings"
	"time"

	"IBootTime/internal/config"
	"IBootTime/internal/isomgr"
	"IBootTime/internal/logger"
	"IBootTime/internal/session"

	"github.com/pin/tftp/v3"
)

//go:embed assets/*
var ipxeAssets embed.FS

type Server struct {
	port       int
	listener   net.PacketConn
	server     *tftp.Server
	log        *logger.Logger
	sessions   *session.Manager
	isoMgr     *isomgr.Manager
	cfg        *config.Config
	serverIP   string
	httpPort   int
	cancelFunc context.CancelFunc
}

func New(port int, serverIP string, httpPort int, log *logger.Logger, sessions *session.Manager, isoMgr *isomgr.Manager, cfg *config.Config) *Server {
	return &Server{
		port:     port,
		log:      log,
		sessions: sessions,
		isoMgr:   isoMgr,
		cfg:      cfg,
		serverIP: serverIP,
		httpPort: httpPort,
	}
}

func (s *Server) Start(ctx context.Context) error {
	ctx, cancel := context.WithCancel(ctx)
	s.cancelFunc = cancel

	s.server = tftp.NewServer(s.readHandler, nil)
	s.server.SetTimeout(10 * time.Second)

	addr := fmt.Sprintf(":%d", s.port)

	s.log.Info("TFTP", "Starting TFTP server on %s", addr)

	var err error
	s.listener, err = net.ListenPacket("udp4", addr)
	if err != nil {
		cancel()
		return fmt.Errorf("TFTP listen: %w", err)
	}

	go func() {
		<-ctx.Done()
		s.listener.Close()
	}()

	go func() {
		if err := s.server.Serve(s.listener.(*net.UDPConn)); err != nil {
			if ctx.Err() == nil {
				s.log.Error("TFTP", "Server error: %v", err)
			}
		}
	}()

	return nil
}

func (s *Server) Stop() {
	if s.cancelFunc != nil {
		s.cancelFunc()
	}
	if s.server != nil {
		s.server.Shutdown()
	}
	s.log.Info("TFTP", "TFTP server stopped")
}

func (s *Server) readHandler(filename string, rf io.ReaderFrom) error {
	raddr := rf.(tftp.OutgoingTransfer).RemoteAddr()
	clientIP := raddr.IP.String()

	s.log.Info("TFTP", "Request from %s for file: %s", clientIP, filename)

	filename = strings.TrimPrefix(filename, "/")

	switch filename {
	case "undionly.kpxe", "ipxe.efi", "snp.efi":
		return s.serveEmbeddedBinary(filename, rf)
	case "grubx64.efi", "grub2pxe":
		return s.serveEmbeddedBinary(filename, rf)
	case "grub.cfg", "grub/grub.cfg":
		return s.serveGRUBConfig(rf)
	case "boot.ipxe", "autoboot.ipxe":
		return s.serveIPXEScript(rf)
	default:
		s.log.Warn("TFTP", "File not found: %s (from %s)", filename, clientIP)
		return fmt.Errorf("file not found: %s", filename)
	}
}

func (s *Server) serveEmbeddedBinary(filename string, rf io.ReaderFrom) error {
	data, err := ipxeAssets.ReadFile("assets/" + filename)
	if err != nil {
		s.log.Error("TFTP", "Asset not found: %s (add the binary to internal/tftpsrv/assets/)", filename)
		return fmt.Errorf("asset not found: %s", filename)
	}

	// Detect placeholder files (< 1KB) and fallback to ipxe.efi for UEFI binaries.
	// snp.efi may be a placeholder — ipxe.efi works on most real UEFI hardware.
	if len(data) < 1024 && filename != "undionly.kpxe" {
		s.log.Warn("TFTP", "%s is a placeholder (%d bytes), falling back to ipxe.efi", filename, len(data))
		fallback, fbErr := ipxeAssets.ReadFile("assets/ipxe.efi")
		if fbErr == nil && len(fallback) > 1024 {
			data = fallback
			s.log.Info("TFTP", "Using ipxe.efi (%d bytes) as fallback for %s", len(data), filename)
		} else {
			s.log.Error("TFTP", "Fallback ipxe.efi also unavailable — PXE boot will fail on real hardware")
		}
	}

	reader := bytes.NewReader(data)
	n, err := rf.ReadFrom(reader)
	if err != nil {
		s.log.Error("TFTP", "Error sending %s: %v", filename, err)
		return err
	}

	s.log.Info("TFTP", "Sent %s (%d bytes)", filename, n)
	return nil
}

func (s *Server) serveGRUBConfig(rf io.ReaderFrom) error {
	isos := s.isoMgr.ListEnabled()

	var cfg strings.Builder
	cfg.WriteString("# GRUB Configuration - Generated by IBootTime\n")
	cfg.WriteString("set default=0\n")
	cfg.WriteString("set timeout=30\n")
	cfg.WriteString(fmt.Sprintf("set server_ip=%s\n", s.serverIP))
	cfg.WriteString(fmt.Sprintf("set http_port=%d\n", s.httpPort))
	cfg.WriteString("\n")

	cfg.WriteString("menuentry \"========================================\" {\n  true\n}\n")
	cfg.WriteString("menuentry \"     IBootTime - Network Boot Server\" {\n  true\n}\n")
	cfg.WriteString("menuentry \"========================================\" {\n  true\n}\n\n")

	if len(isos) > 0 {
		cfg.WriteString("menuentry \"--- ISOs disponibles ---\" {\n  true\n}\n\n")
		for _, iso := range isos {
			cfg.WriteString(fmt.Sprintf("menuentry \"%s [%s] (%s)\" {\n", iso.Name, iso.OSType, iso.SizeHR))

			switch iso.OSType {
			case isomgr.OSTypeWindows, isomgr.OSTypeWinPE:
				cfg.WriteString(fmt.Sprintf("  echo \"Cargando %s...\"\n", iso.Name))
				cfg.WriteString(fmt.Sprintf("  set isofile=\"(http,$server_ip:$http_port)/iso/%s/raw\"\n", iso.Name))
				cfg.WriteString("  loopback loop $isofile\n")
				cfg.WriteString("  set root=(loop)\n")
				cfg.WriteString("  chainloader /efi/boot/bootx64.efi\n")
			case isomgr.OSTypeLinux:
				cfg.WriteString(fmt.Sprintf("  echo \"Cargando %s...\"\n", iso.Name))
				cfg.WriteString(fmt.Sprintf("  set isofile=\"(http,$server_ip:$http_port)/iso/%s/raw\"\n", iso.Name))
				cfg.WriteString("  loopback loop $isofile\n")
				cfg.WriteString("  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile\n")
				cfg.WriteString("  initrd (loop)/casper/initrd\n")
			default:
				cfg.WriteString(fmt.Sprintf("  echo \"Cargando %s...\"\n", iso.Name))
				cfg.WriteString(fmt.Sprintf("  set isofile=\"(http,$server_ip:$http_port)/iso/%s/raw\"\n", iso.Name))
				cfg.WriteString("  loopback loop $isofile\n")
			}

			cfg.WriteString("  boot\n")
			cfg.WriteString("}\n\n")
		}
	}

	cfg.WriteString("menuentry \"Reiniciar equipo\" {\n")
	cfg.WriteString("  reboot\n")
	cfg.WriteString("}\n\n")

	cfg.WriteString("menuentry \"Apagar equipo\" {\n")
	cfg.WriteString("  halt\n")
	cfg.WriteString("}\n")

	grubCfg := cfg.String()
	s.log.Info("TFTP", "Serving GRUB config (%d bytes, %d ISOs)", len(grubCfg), len(isos))

	reader := strings.NewReader(grubCfg)
	_, err := rf.ReadFrom(reader)
	return err
}

func (s *Server) serveIPXEScript(rf io.ReaderFrom) error {
	bootProto := s.cfg.GetBootProtocol()

	if bootProto == config.BootProtocolUndionly {
		script := "#!ipxe\necho IBootTime - Undionly Mode (iPXE Shell)\necho Escribe 'dhcp' para obtener IP, luego bootea manualmente.\nshell\n"
		s.log.Info("TFTP", "Serving UNDIONLY boot.ipxe (%d bytes)", len(script))
		reader := strings.NewReader(script)
		_, err := rf.ReadFrom(reader)
		return err
	}

	// Generate FULL iPXE menu script inline.
	// This is critical for clients like VirtualBox's built-in iPXE that
	// have NO HTTP support (Features: DNS TFTP PXE PXEXT — no HTTP).
	// We CANNOT chainload to http:// — must serve everything via TFTP.
	isos := s.isoMgr.ListEnabled()

	var script strings.Builder
	script.WriteString("#!ipxe\n\n")

	// Variables — use TFTP since HTTP may not be available
	script.WriteString("set menu-timeout 0\n")
	script.WriteString(fmt.Sprintf("set server-ip %s\n", s.serverIP))
	script.WriteString(fmt.Sprintf("set http-root http://${server-ip}:%d\n\n", s.httpPort))

	// Menu
	script.WriteString(":start\n")
	script.WriteString("menu IBootTime - Network Boot Server [${server-ip}]\n")
	script.WriteString("item --gap --             ========================================\n")
	script.WriteString("item --gap --                    Sistema de Boot por Red\n")
	script.WriteString("item --gap --             ========================================\n")

	if len(isos) > 0 {
		script.WriteString("item --gap --\n")
		script.WriteString("item --gap -- --- ISOs disponibles ---\n")
		for _, iso := range isos {
			itemID := sanitizeMenuID(iso.Name)
			label := fmt.Sprintf("  %s  [%s] (%s)", iso.Name, string(iso.OSType), iso.SizeHR)
			script.WriteString(fmt.Sprintf("item %s %s\n", itemID, label))
		}
	} else {
		script.WriteString("item --gap --\n")
		script.WriteString("item --gap -- (No hay ISOs configuradas)\n")
		script.WriteString("item --gap -- Agrega ISOs desde el panel de IBootTime\n")
	}

	script.WriteString("item --gap --\n")
	script.WriteString("item --gap -- ========================================\n")
	script.WriteString("item reboot           Reiniciar equipo\n")
	script.WriteString("item shell            iPXE Shell\n")
	script.WriteString("item exit             Salir al firmware\n")
	script.WriteString("choose --timeout ${menu-timeout} --default reboot selected || goto exit\n")
	script.WriteString("goto ${selected}\n\n")

	// ISO boot handlers
	for _, iso := range isos {
		itemID := sanitizeMenuID(iso.Name)
		encodedName := strings.ReplaceAll(iso.Name, " ", "%20")
		script.WriteString(fmt.Sprintf(":%s\n", itemID))
		script.WriteString(fmt.Sprintf("echo Cargando %s ...\n", iso.Name))

		switch iso.OSType {
		case isomgr.OSTypeWindows, isomgr.OSTypeWinPE:
			// Detect UEFI vs BIOS — wimboot on UEFI REQUIRES bootx64.efi
			script.WriteString(fmt.Sprintf("imgfree\n"))
			script.WriteString(fmt.Sprintf("iseq ${platform} efi && goto win_uefi_%s ||\n\n", itemID))

			// ==== BIOS path ====
			script.WriteString(fmt.Sprintf(":win_bios_%s\n", itemID))
			script.WriteString(fmt.Sprintf("kernel ${http-root}/wimboot || goto failed\n"))
			// BCD: try boot/bcd (BIOS) first, then efi/microsoft/boot/bcd
			script.WriteString(fmt.Sprintf("initrd --name BCD ${http-root}/iso/%s/file/boot/bcd BCD || goto win_bcd_efi_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("goto win_sdi_%s\n", itemID))
			script.WriteString(fmt.Sprintf(":win_bcd_efi_%s\n", itemID))
			script.WriteString(fmt.Sprintf("initrd --name BCD ${http-root}/iso/%s/file/efi/microsoft/boot/bcd BCD || goto failed\n", encodedName))
			script.WriteString(fmt.Sprintf(":win_sdi_%s\n", itemID))
			script.WriteString(fmt.Sprintf("initrd --name boot.sdi ${http-root}/iso/%s/file/boot/boot.sdi boot.sdi || goto failed\n", encodedName))
			script.WriteString(fmt.Sprintf("initrd --name boot.wim ${http-root}/iso/%s/file/sources/boot.wim boot.wim || goto failed\n", encodedName))
			script.WriteString("boot || goto failed\n\n")

			// ==== UEFI path ====
			script.WriteString(fmt.Sprintf(":win_uefi_%s\n", itemID))
			script.WriteString(fmt.Sprintf("kernel ${http-root}/wimboot || goto failed\n"))
			// UEFI: bootx64.efi is REQUIRED for wimboot to hand off to Windows Boot Manager
			script.WriteString(fmt.Sprintf("initrd --name bootx64.efi ${http-root}/iso/%s/file/efi/boot/bootx64.efi bootx64.efi || goto failed\n", encodedName))
			// BCD: try efi/microsoft/boot/bcd first, then boot/bcd
			script.WriteString(fmt.Sprintf("initrd --name BCD ${http-root}/iso/%s/file/efi/microsoft/boot/bcd BCD || goto win_uefi_bcd_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("goto win_uefi_sdi_%s\n", itemID))
			script.WriteString(fmt.Sprintf(":win_uefi_bcd_%s\n", itemID))
			script.WriteString(fmt.Sprintf("initrd --name BCD ${http-root}/iso/%s/file/boot/bcd BCD || goto failed\n", encodedName))
			script.WriteString(fmt.Sprintf(":win_uefi_sdi_%s\n", itemID))
			script.WriteString(fmt.Sprintf("initrd --name boot.sdi ${http-root}/iso/%s/file/boot/boot.sdi boot.sdi || goto failed\n", encodedName))
			script.WriteString(fmt.Sprintf("initrd --name boot.wim ${http-root}/iso/%s/file/sources/boot.wim boot.wim || goto failed\n", encodedName))
			script.WriteString("boot || goto failed\n\n")

		case isomgr.OSTypeLinux:
			// Ubuntu/Casper
			script.WriteString("imgfree\n")
			script.WriteString(fmt.Sprintf("kernel ${http-root}/iso/%s/file/casper/vmlinuz boot=casper netboot=url url=${http-root}/iso/%s/raw ip=dhcp -- || goto linux_live_%s\n", encodedName, encodedName, itemID))
			script.WriteString(fmt.Sprintf("initrd ${http-root}/iso/%s/file/casper/initrd || goto linux_live_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("boot || goto sanboot_%s\n", itemID))
			// Debian/Live
			script.WriteString(fmt.Sprintf(":linux_live_%s\n", itemID))
			script.WriteString("imgfree\n")
			script.WriteString(fmt.Sprintf("kernel ${http-root}/iso/%s/file/live/vmlinuz boot=live fetch=${http-root}/iso/%s/file/live/filesystem.squashfs ip=dhcp -- || goto linux_isolinux_%s\n", encodedName, encodedName, itemID))
			script.WriteString(fmt.Sprintf("initrd ${http-root}/iso/%s/file/live/initrd.img || goto linux_isolinux_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("boot || goto sanboot_%s\n", itemID))
			// Isolinux/Syslinux
			script.WriteString(fmt.Sprintf(":linux_isolinux_%s\n", itemID))
			script.WriteString("imgfree\n")
			script.WriteString(fmt.Sprintf("kernel ${http-root}/iso/%s/file/isolinux/vmlinuz -- || goto sanboot_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("initrd ${http-root}/iso/%s/file/isolinux/initrd.img || goto sanboot_%s\n", encodedName, itemID))
			script.WriteString(fmt.Sprintf("boot || goto sanboot_%s\n", itemID))
			// Fallback: SAN boot
			script.WriteString(fmt.Sprintf(":sanboot_%s\n", itemID))
			script.WriteString(fmt.Sprintf("echo Kernel no encontrado, intentando sanboot para %s ...\n", iso.Name))
			script.WriteString("imgfree\n")
			script.WriteString(fmt.Sprintf("sanboot --no-describe ${http-root}/iso/%s/raw || goto failed\n\n", encodedName))

		default:
			script.WriteString(fmt.Sprintf("sanboot ${http-root}/iso/%s/raw || goto failed\n\n", encodedName))
		}
	}

	// Utility handlers
	script.WriteString(":failed\n")
	script.WriteString("echo\n")
	script.WriteString("echo ERROR: No se pudo arrancar la imagen seleccionada.\n")
	script.WriteString("echo Verifica que la ISO este correctamente configurada.\n")
	script.WriteString("prompt Presiona ENTER para volver al menu...\n")
	script.WriteString("goto start\n\n")

	script.WriteString(":reboot\nreboot\n\n")
	script.WriteString(":shell\necho Escribe 'exit' para volver al menu\nshell\ngoto start\n\n")
	script.WriteString(":exit\nexit\n")

	result := script.String()
	s.log.Info("TFTP", "Serving FULL boot.ipxe menu (%d bytes, %d ISOs)", len(result), len(isos))
	reader := strings.NewReader(result)
	_, err := rf.ReadFrom(reader)
	return err
}

func sanitizeMenuID(name string) string {
	name = strings.TrimSuffix(strings.ToLower(name), ".iso")
	replacer := strings.NewReplacer(" ", "-", ".", "-", "_", "-", "(", "", ")", "")
	return replacer.Replace(name)
}

func (s *Server) SetServerIP(ip string) {
	s.serverIP = ip
}
