// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseISODirectory() {
  return window['go']['main']['App']['BrowseISODirectory']();
}

export function GetBootProtocol() {
  return window['go']['main']['App']['GetBootProtocol']();
}

export function GetConnectedClients() {
  return window['go']['main']['App']['GetConnectedClients']();
}

export function GetISODirectory() {
  return window['go']['main']['App']['GetISODirectory']();
}

export function GetISOList() {
  return window['go']['main']['App']['GetISOList']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSelectedInterface() {
  return window['go']['main']['App']['GetSelectedInterface']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ScanISOs() {
  return window['go']['main']['App']['ScanISOs']();
}

export function SetBootProtocol(arg1) {
  return window['go']['main']['App']['SetBootProtocol'](arg1);
}

export function SetISODirectory(arg1) {
  return window['go']['main']['App']['SetISODirectory'](arg1);
}

export function SetNetworkInterface(arg1) {
  return window['go']['main']['App']['SetNetworkInterface'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ToggleISO(arg1, arg2) {
  return window['go']['main']['App']['ToggleISO'](arg1, arg2);
}
