// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentproxy} from '../models';
import {session} from '../models';
import {isomgr} from '../models';
import {netinfo} from '../models';
import {logger} from '../models';
import {orchestrator} from '../models';

export function AgentCreateTestFile(arg1:string):Promise<agentproxy.TaskResponse>;

export function AgentGetTasks(arg1:string):Promise<Array<agentproxy.RemoteTask>>;

export function AgentListClients():Promise<Array<agentproxy.RemoteClient>>;

export function AgentOpenNotepad(arg1:string):Promise<agentproxy.TaskResponse>;

export function AgentPing(arg1:string):Promise<agentproxy.TaskResponse>;

export function AssignISO(arg1:string,arg2:string):Promise<boolean>;

export function BrowseISODirectory():Promise<string>;

export function BrowseISOUnattend(arg1:string):Promise<string>;

export function ClearISOUnattend(arg1:string):Promise<void>;

export function GetBootProtocol():Promise<string>;

export function GetConnectedClients():Promise<Array<session.ClientSession>>;

export function GetISODirectory():Promise<string>;

export function GetISOList():Promise<Array<isomgr.ISOInfo>>;

export function GetNetworkInterfaces():Promise<Array<netinfo.NetInterface>>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetSelectedInterface():Promise<string>;

export function GetServerStatus():Promise<orchestrator.ServiceStatus>;

export function GetWinPERemote():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function ScanISOs():Promise<Array<isomgr.ISOInfo>>;

export function SetBootProtocol(arg1:string):Promise<void>;

export function SetISODirectory(arg1:string):Promise<void>;

export function SetISOUnattend(arg1:string,arg2:string):Promise<void>;

export function SetNetworkInterface(arg1:string):Promise<void>;

export function SetWinPERemote(arg1:boolean):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function ToggleISO(arg1:string,arg2:boolean):Promise<void>;

export function TriggerRemote(arg1:string):Promise<void>;
