// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentCreateTestFile(arg1) {
  return window['go']['main']['App']['AgentCreateTestFile'](arg1);
}

export function AgentGetTasks(arg1) {
  return window['go']['main']['App']['AgentGetTasks'](arg1);
}

export function AgentListClients() {
  return window['go']['main']['App']['AgentListClients']();
}

export function AgentOpenNotepad(arg1) {
  return window['go']['main']['App']['AgentOpenNotepad'](arg1);
}

export function AgentPing(arg1) {
  return window['go']['main']['App']['AgentPing'](arg1);
}

export function AssignISO(arg1, arg2) {
  return window['go']['main']['App']['AssignISO'](arg1, arg2);
}

export function BrowseISODirectory() {
  return window['go']['main']['App']['BrowseISODirectory']();
}

export function BrowseISOUnattend(arg1) {
  return window['go']['main']['App']['BrowseISOUnattend'](arg1);
}

export function ClearISOUnattend(arg1) {
  return window['go']['main']['App']['ClearISOUnattend'](arg1);
}

export function GetBootProtocol() {
  return window['go']['main']['App']['GetBootProtocol']();
}

export function GetConnectedClients() {
  return window['go']['main']['App']['GetConnectedClients']();
}

export function GetISODirectory() {
  return window['go']['main']['App']['GetISODirectory']();
}

export function GetISOList() {
  return window['go']['main']['App']['GetISOList']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetSelectedInterface() {
  return window['go']['main']['App']['GetSelectedInterface']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetWinPERemote() {
  return window['go']['main']['App']['GetWinPERemote']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ScanISOs() {
  return window['go']['main']['App']['ScanISOs']();
}

export function SetBootProtocol(arg1) {
  return window['go']['main']['App']['SetBootProtocol'](arg1);
}

export function SetISODirectory(arg1) {
  return window['go']['main']['App']['SetISODirectory'](arg1);
}

export function SetISOUnattend(arg1, arg2) {
  return window['go']['main']['App']['SetISOUnattend'](arg1, arg2);
}

export function SetNetworkInterface(arg1) {
  return window['go']['main']['App']['SetNetworkInterface'](arg1);
}

export function SetWinPERemote(arg1) {
  return window['go']['main']['App']['SetWinPERemote'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ToggleISO(arg1, arg2) {
  return window['go']['main']['App']['ToggleISO'](arg1, arg2);
}

export function TriggerRemote(arg1) {
  return window['go']['main']['App']['TriggerRemote'](arg1);
}
